apiVersion: v1
kind: Service
metadata:
  name: {{DEPLOYMENT_NAME}}-service
  namespace: {{NAMESPACE}}
spec:
  selector:
    app: {{DEPLOYMENT_NAME}}
  ports:
    - protocol: TCP
      port: {{SERVICE_PORT}}
      targetPort: {{CONTAINER_PORT}}
  type: {{SERVICE_TYPE}}

